# Generated by Django 5.2.1 on 2025-06-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
